accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from . import views

app_name = "accountapp"

urlpatterns = [
    path('', views.hello_world, name='hello_world'),
    path('create/', views.AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', views.AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', views.AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.AccountDeleteView.as_view(), name='delete'),
    path('login/', LoginView.as_view(template_name = 'accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name = 'logout'),


]

infoapp/urls.py
from django.urls import path
from . import views

app_name = 'infoapp'

urlpatterns = [

    path('info/', views.info, name='info'),
    path('notice/', views.notice, name='notice'),
    path('contact/', views.contact, name='contact'),
    path('company/', views.company, name='company'),
]

profileapp/urls.py
from django.urls import path
from . import views

app_name= 'profileapp'


#views의 함수와 url들 연결
urlpatterns = [
    path('create/', views.ProfileCreateView.as_view(), name='create'),
    path('update/<int:pk>/', views.ProfileUpdateView.as_view(), name='update'),
]

zzalbang/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView, ArticleMainList

urlpatterns = [
    path('', ArticleMainList.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include("accountapp.urls")),
    path('profiles/', include("profileapp.urls")),
    path('articles/', include('articleapp.urls')),
    path('comments/', include("commentapp.urls")),
    path('gallery/', include("galleryapp.urls")),
    path('subscribe/', include("subscribeapp.urls")),
    path('likes/', include("likeapp.urls")),

    path('infos/', include("infoapp.urls")),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path('summernote/', include('django_summernote.urls')),

]

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models

from galleryapp.models import Gallery


class Article(models.Model):
    #유저객체와 포린키로 연결, 유저가 탈퇴해도 게시글은 사라지지 않는다
    #유저객체에서 Article객체에 접근할 때 쓸 이름은 article, set_NULL으로 한다고 했으니 당연히 null=True 입력해줘야함
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='ariticle', null=True)
    title = models.CharField(max_length=200)
    #저장위지 반드시 저장
    image = models.ImageField(upload_to='article/', null=False)
    #내용작성 필드
    content = models.TextField(null=True, blank=True)
    #작성날짜, add로 게시글 생성했을 때의 시간으로 저장됨.
    created_at = models.DateTimeField(auto_now_add=True)


    #갤러리 객체와 포린키로 연결.  갤러리 지워저도 article들 안지워짐, 갤러리로 부터 article을 참조하는 역참조(related name) 이름은 article
    gallery = models.ForeignKey(Gallery, on_delete=models.SET_NULL, null=True, blank=True, related_name='article')

    like = models.IntegerField(default=0)


    def __str__(self):
        return self.title

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm


class AccountUpdateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        #UserCreationForm 이라는 장고가 제공하는 폼을 이용하는데 한가지 기능을 추가할 것이다
        #아이디는 바꿀수 없게 하겠다.
        self.fields['username'].disabled =True

accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponseForbidden
from django.shortcuts import render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView
from django.views.generic.list import MultipleObjectMixin

from accountapp.decorator import account_ownership_required
from accountapp.forms import AccountUpdateForm
from articleapp.models import Article

has_ownership = [account_ownership_required, login_required]

def hello_world(request):
    return render(request, 'accountapp/hello.html')

class AccountCreateView(CreateView):
    #유저라는 모델로 CreatView를 만들것이다.
    model = User
    #User 모델을 만들기위한 폼은 UserCreationForm을 이용할 것이다.
    form_class = UserCreationForm
    #계정생성을 성공하면 리다이렉트할 위치
    success_url = reverse_lazy('accountapp:hello_world')
    #UserCreationForm을 찍어낼 template 즉 html은 무엇을 사용할 것인가
    template_name = 'accountapp/create.html'


class AccountDetailView(DetailView,MultipleObjectMixin):
    #어떤 모델을 쓸건지
    model = User
    #어떤 템플릿에서 시각화해서 보여줄 것인지
    template_name = 'accountapp/detail.html'
    #위의 템플릿에서 User 모델을 어떤 변수명으로 사용할 것인지
    context_object_name = 'target_user'

    paginate_by = 12

    def get_context_data(self, **kwargs):
        object_list = Article.objects.filter(writer=self.get_object())
        return super(AccountDetailView, self).get_context_data(object_list=object_list, **kwargs)

#method_decorator라는 번역기를 달아서, 클래스 안의 메소드에도 작용하도록
# import를 has_ownership으로 묶어 주고, 두 줄로 줄임
@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountUpdateView(UpdateView):
    #어떤 모델을 쓸건지
    model = User
    #User 모델의 정보를 수정하기 위한 폼은 AccoutUpdateForm으로 할 것이다.
    form_class = AccountUpdateForm
    #계정정보 수정을 성공하면 리다이렉트 위치를 정해준다
    success_url = reverse_lazy('accountapp:hello_world')
    #정보수정을 할 때 html은 어떤 template html을 쓸 것인지
    template_name = 'accountapp/update.html'
    #위의 html에서 User모델을 어떤 변수로 화면출력이 되게 할 것인가
    context_object_name = 'target_user'

    #겟요청 처리 겟 메소드 오버라이딩

#method_decorator라는 번역기를 달아서, 클래스 안의 메소드에도 작용하도록
@method_decorator(has_ownership, 'get')
@method_decorator(has_ownership, 'post')
class AccountDeleteView(DeleteView):
    #어떤 모델을 쓸건지
    model = User
    #회원 탈퇴가 성공하면 어디로 리다이렉트 할 것인지
    Success_url = reverse_lazy('accountapp:login')
    #회원탈퇴 할 때 쓸 html은 어떤 template html 이용할 것인지
    template_name = 'accountapp/delete.html'
    #위의 템플릿에서 User모델을 어떤 변수명으로 사용할 것인지
    context_object_name = 'target_user'

    # 겟요청 처리 겟 메소드 오버라이딩
    #지우고 데코레이션 함수 로 대체

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
  <div style="text-align: center; max-width: 500px; margin: 4rem auto">
      <form action="{% url 'accountapp:create' %}" method="post">
          {% csrf_token %}
          {% bootstrap_form form %}
          <input type="submit" class="btn btn-primary">
      </form>
  </div>



{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

<div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div class="mb-4">
      <h4>회원탈퇴</h4>
    </div>
    <!-- accountapp 의 delete 라우트로 post 요청을 보낼것이다 -->
    <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method="post">
      {% csrf_token %}
      <input type="submit" class="btn btn-danger rounded-pill col-6 mt-3">
    </form>
</div>

{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}

{% block content %}
  <div>
    <div style="text-align: center; max-width: 500px; margin: 4rem auto;">
      {% if target_user.profile %}
        <!-- 프로필 이미지 -->
        <img src="{{ target_user.profile.image.url }}" alt="" style="height: 12rem; width: 12rem; border-radius: 20rem; margin-bottom: 2rem; object-fit: cover;"/>
        <h2 style="font-weight: bold;">
          {{ target_user.profile.nickname }}
        </h2>
        <!-- 프로필메세지 -->
        <h5 style="margin-bottom:3rem;">
          {{ target_user.profile.message }}
        </h5>
      {% if target_user == request.user %}
      <!-- 프로필 수정 타겟유저가 진짜 주인 유저일때 -->
        <a href="{% url 'profileapp:update' pk=target_user.profile.pk %}">
          프로필수정
        </a>
        <br /><br />
      {% endif %}
      {% else %}
        {% if target_user == request.user %}
        <a href="{% url 'profileapp:create' %}">
          <span class="material-icons" style="font-size: 3rem;" >
            person_add_alt_1
          </span>
          <h2 style="font-weight: bold;">
            프로필생성
          </h2>
        </a>
        {% endif %}
      {% endif %}
      {% if target_user == request.user %}
        <a title="회원정보수정" class="material-icons" href="{% url 'accountapp:update' pk=user.pk %}" style="box-shadow: 0 0 5px #bbb; boarder-radius: 50%; padding: 0.45rem;">
          settings
        </a>
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <a title="회원탈퇴" class="material-icons" href="{% url 'accountapp:delete' pk=target_user.pk %}" style="box-shadow: 0 0 5px #fcb; boarder-radius: 50%; padding: 0.45rem;">
          cancel
        </a>
      {% endif %}
    </div>

    <!-- object_list 는 accountapp 의 views.py 의 get_context_data 로부터 넘어온 값  -->
    <div>
      {% include 'piece/list_fragment.html' with article_list=object_list %}
    </div>



  </div>
{% endblock %}

accountapp/templates/accountapp/hello.html
{% extends 'base.html' %}
{% block content %}


{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div>
            <h4>Login</h4>
        </div>
        <div>
            <form action="" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                <input type="submit" class="btn btn-primary">
            </form>
        </div>
    </div>
{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

  <div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div class="mb-4">
      <h4>회원정보 수정</h4>
    </div>
    <!-- accountapp 의 update 라우트로 post 요청을 보낼것이다 -->
    <form action="{% url 'accountapp:update' pk=target_user.pk %}" method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
  </div>

{% endblock %}