articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = 'articleapp'

urlpatterns = [
     path('list/', views.ArticleListView.as_view(), name='list'),
     path('create/', views.ArticleCreateView.as_view(), name='create'),
     path('detail/<int:pk>/', views.ArticleDetailView.as_view(), name='detail'),
     path('update/<int:pk>/', views.ArticleUpdateView.as_view(), name='update'),

     path('delete/<int:pk>/', views.ArticleDeleteView.as_view(), name='delete'),

]

galleryapp/urls.py
from django.urls import path
from . import views

app_name = 'galleryapp'

urlpatterns = [
    path('create/', views.GalleryCreateView.as_view(), name='create'),
    path('detail/<int:pk>/', views.GalleryDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', views.GalleryUpdateView.as_view(), name='update'),
    path('list/', views.GalleryListView.as_view(), name='list'),

]

infoapp/urls.py
from django.urls import path
from . import views

app_name = 'infoapp'

urlpatterns = [

    path('info/', views.info, name='info'),
    path('notice/', views.notice, name='notice'),
    path('contact/', views.contact, name='contact'),
    path('company/', views.company, name='company'),
]

subscribeapp/urls.py
from django.urls import path
from . import views

app_name='subscribeapp'

urlpatterns = [
    path('subscribe/', views.SubscriptionView.as_view(), name='subscribe'),
    path('list/', views.SubscriptionListView.as_view(), name='list'),
]

zzalbang/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView, ArticleMainList

urlpatterns = [
    path('', ArticleMainList.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include("accountapp.urls")),
    path('profiles/', include("profileapp.urls")),
    path('articles/', include('articleapp.urls')),
    path('comments/', include("commentapp.urls")),
    path('gallery/', include("galleryapp.urls")),
    path('subscribe/', include("subscribeapp.urls")),
    path('likes/', include("likeapp.urls")),

    path('infos/', include("infoapp.urls")),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path('summernote/', include('django_summernote.urls')),

]

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models

from galleryapp.models import Gallery


class Article(models.Model):
    #유저객체와 포린키로 연결, 유저가 탈퇴해도 게시글은 사라지지 않는다
    #유저객체에서 Article객체에 접근할 때 쓸 이름은 article, set_NULL으로 한다고 했으니 당연히 null=True 입력해줘야함
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='ariticle', null=True)
    title = models.CharField(max_length=200)
    #저장위지 반드시 저장
    image = models.ImageField(upload_to='article/', null=False)
    #내용작성 필드
    content = models.TextField(null=True, blank=True)
    #작성날짜, add로 게시글 생성했을 때의 시간으로 저장됨.
    created_at = models.DateTimeField(auto_now_add=True)


    #갤러리 객체와 포린키로 연결.  갤러리 지워저도 article들 안지워짐, 갤러리로 부터 article을 참조하는 역참조(related name) 이름은 article
    gallery = models.ForeignKey(Gallery, on_delete=models.SET_NULL, null=True, blank=True, related_name='article')

    like = models.IntegerField(default=0)


    def __str__(self):
        return self.title

galleryapp/models.py
from django.contrib.auth.models import User
from django.db import models

class Gallery(models.Model):
    #갤러리 썸네일
    image = models.ImageField(upload_to='gallery/', null=False)
    #갤러리 이름
    title = models.CharField(max_length=20, null=False)
    #갤러리 설명
    description = models.CharField(max_length=200, null=False)
    #갤러리 생성날짜
    created_at = models.DateTimeField(auto_now_add=True)
    #작성자
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.title

galleryapp/forms.py
from django.forms import ModelForm

from galleryapp.models import Gallery


class GalleryCreationForm(ModelForm):
    class Meta:
        # 모델은
        model = Gallery
        #다음과 같은 모델의 필드들을
        fields = ['image', 'title', 'description']

galleryapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, ListView
from django.views.generic.list import MultipleObjectMixin

from articleapp.models import Article
from galleryapp.decorators import gallery_ownership_required
from galleryapp.forms import GalleryCreationForm
from galleryapp.models import Gallery
from subscribeapp.models import Subscription


@method_decorator(login_required, 'get')
@method_decorator(login_required, 'post')
class GalleryCreateView(CreateView):
    #모델은 갤러리
    model = Gallery
    #갤리리 모델로 부터 Gallery 인스턴스를 생성하기위해 사용할 Form은 GalleryCreationForm이다
    form_class = GalleryCreationForm
    #위 GalleryCreationForm을 찍어낼 html은 galleryapp의 create.html 이다.
    template_name = 'galleryapp/create.html'

  #over-riding 방법
    def form_valid(self, form):
        temp_gallery = form.save(commit=False)
        temp_gallery.writer = self.request.user
        temp_gallery.save()
        return super().form_valid(form)

    #Gallery 인스턴스객체가 성공적으로 생성이되면 이동할 html
    #GalleryCreationForm 으로 막 생성한 특정갤러리의 디테일 페이지로 이동
    def get_success_url(self):
        return reverse('galleryapp:detail', kwargs={'pk': self.object.pk})

#MultipleObjectMixin은 여러가지 object들을 다룰 수 있게 만들어 주는 클래스
class GalleryDetailView(DetailView, MultipleObjectMixin):
    model = Gallery
    template_name = 'galleryapp/detail.html'
    context_object_name = 'target_gallery'
    #
    paginate_by = 20
    # 아래 겟컨텍스트  는 템플릿으로 무언가(인스턴스)를 출력하고 싶을 때 쓰는 메소드
    def get_context_data(self, **kwargs):
        #특정 pk 값을 갖는 갤러리 한개를 gallery변수에 담는다
        gallery = self.object
        #구독버튼을 누른 유저를 user변수에 담는다.
        user = self.request.user
        #유저가 인증된 유저라면 즉 로그인 했다면
        if user.is_authenticated:
            subscription = Subscription.objects.filter(user=user, gallery=gallery)
        else:
            subscription = None

        #get_object()는 특정 pk값을 갖는 object를 가져오는 메소드. 여기서는 Gallery 한개.
        #Article객체를 필터링 한다. gallery 필드가 특정 Gallery로 채워진 Article들로
        object_list = Article.objects.filter(gallery=self.get_object()).order_by('-pk')
        return super(GalleryDetailView, self).get_context_data(object_list=object_list, subscription=subscription,  **kwargs)


@method_decorator(gallery_ownership_required, 'get')
@method_decorator(gallery_ownership_required, 'post')
class GalleryUpdateView(UpdateView):
    #모델
    model = Gallery
    #사용자 입력 폼
    form_class = GalleryCreationForm
    #html
    template_name = 'galleryapp/update.html'
    #인스턴스
    context_object_name = 'target_gallery'


    #성공하면

    def get_success_url(self):
        return reverse('galleryapp:detail', kwargs={'pk': self.object.pk})

 #galery_list.html이 디폴트 이지만, 우리가 새 이름 지정
class GalleryListView(ListView):
    #어떤 모델 쓸것인가
    model = Gallery
    #갤러리 리스트 뭉탱이를 찍어내는 html은 어떤 html을 쓸 것인가?
    template_name = 'galleryapp/List.html'
    #위의 html에서 어떤이름으로 갤러리 리스트 뭉탱이를 표현할 것인가
    context_object_name = 'gallery_list'
    #갤러리를 몇개식 만들기
    paginate_by = 12

galleryapp/templates/galleryapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

  <div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div class="mb-4">
      <h4>Create Gallery</h4>
    </div>
    <form action="{% url 'galleryapp:create' %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
  </div>

{% endblock %}

galleryapp/templates/galleryapp/detail.html
{% extends 'base.html' %}

{% block content %}

  <div>
    <div style="text-align: center; max-width: 500px; margin: 4rem auto;">
      <script type="text/javascript">

#만약 Kakao개발자 js 키를 넣어야 한다면 여기일까? 스티커에
Kakao.init('3f8ce7338f851333ceada7fcfc7af800'); // 초기화

Kakao.Link.createDefaultButton({
    container: '#create-kakao-link-btn',
    objectType: 'feed',
    content: {
      title: '{{ target_gallery.title }}',
      description: '#wind4sns #{{ target_gallery.title }}',
      imageUrl:
        'https://3zzal.com {{ target_gallery.image.url }}',
      link: {
        mobileWebUrl: 'https://3zzal.com/projects/detail/' + '{{target_gallery.pk}}',
        webUrl: 'https://3zzal.com/projects/detail/' + '{{target_gallery.pk}}' ,
      },
    },
    social: {
      likeCount: 286,
      commentCount: 45,
      sharedCount: 845,
    },
    buttons: [
      {
        title: '웹으로 보기',
        link: {
          mobileWebUrl: 'https://3zzal.com/gallery/detail/' + '{{target_gallery.pk}}',
          webUrl: 'https://3zzal.com/gallery/detail/' + '{{target_gallery.pk}}',
        },
      },
      {
        title: '앱으로 보기',
        link: {
          mobileWebUrl: 'https://3zzal.com/gallery/detail/' + '{{target_gallery.pk}}',
          webUrl: 'https://3zzal.com/gallery/detail/' + '{{target_gallery.pk}}',
        },
      },
    ],
  })
</script>


      <img src="{{ target_gallery.image.url }}" alt=""
           style="height: 12rem; width: 12rem; border-radius: 20rem; margin-bottom: 2rem; object-fit: cover;">
        <p>갤 매니져: <strong style="font-size: 2rem;">{{ target_gallery.writer }}</strong></p>

      {% if target_gallery.writer == request.user %}
      <a title="갤러리수정" href="{% url 'galleryapp:update' pk=target_gallery.pk %}" class="material-icons gall_edit" style="box-shadow: 0 0 4px #ccc; border-radius: 10rem; padding: 0.4rem;">
        edit
      </a>
      {% endif %}

      <h2 style="font-weight:bold;">
        {{ target_gallery.title }}
      </h2>
      <br /><br />
      <h5 style="margin-bottom:3rem;">
        {{ target_gallery.description }}
      </h5>
      <!-- subscibeapp model로 부터 -->

      <!-- articleapp 의 model로 부터 -->
      <span style="font-size: 0.9rem; letter-spacing: 0.01rem;">구독자 <strong style="font-size: 1.3rem;">{{ target_gallery.subscription.count }}</strong> 명 </span>&nbsp;|
      <span style="font-size: 0.9rem; letter-spacing: 0.01rem;">게시물 <strong style="font-size: 1.3rem;">{{ target_gallery.article.count }}</strong> 개 </span>

      <div class="text-center mb-5">
        {% if user.is_authenticated %}
          {% if not subscription %}
          <!-- 구독 중이 아니라면 http 겟 요청으로 ?gallery_pk 의 값인 target_gallery.pk 넘겨줌   -->
          <a href="{% url 'subscribeapp:subscribe' %}?gallery_pk={{ target_gallery.pk}}" class="btn btn-primary rounded-pill px-4">
            구독
          </a>
          <!-- 구독 중이라면 같은 위치로 GET요청으로 정보를 넘겨줌-->
          {% else %}
          <a href="{% url 'subscribeapp:subscribe' %}?gallery_pk={{ target_gallery.pk}}" class="btn btn-secondary rounded-pill px-4">
             구독취소
          </a>
          {% endif %}
        {% endif %}

     </div>

      <!-- object_list = Article.objects.filter(gallery=self.get_object()) -->
      <div>
        {% include 'piece/list_fragment.html' with article_list=object_list  %}
      </div>

      <div style="text-align: center">
        <a href="{% url 'articleapp:create' %}?gallery_pk={{ target_gallery.pk }}" class="btn btn-dark rounded-pill mt-3 mb-3 px-3">
            게시글 생성
        </a>
      </div>

    </div>
  </div>

{% endblock %}

galleryapp/templates/galleryapp/list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- 아티클앱의 list.html 을 그대로 가져옴 그러나 몇가지 이름만 바꿔줌 -->
<!-- 아태클앱의 container a 의 값은 삭제 -->
<!-- 아태클앱의 container img 의 값 픽셀지정 -->
<!-- 오브젝핏 커버는  그사이즈 안에있는것 빼고는 다 짤라내지는 형식으로 구현이됨 -->
<style>

    .container {
        padding: 0;
        margin: 0, auto;
    }

    .container div {
      display: flex;
      justify-content: center;
      align-items: center;

      border-radius: 1rem;
    }

    .container img {
      width: 7rem;
      height: 7rem;
      object-fit: cover;
      border-radius: 1rem;
    }

</style>
    {% if gallery_list %}
    <div class="container">
        {% for gallery in gallery_list %}
        <a href="{% url 'galleryapp:detail' pk=gallery.pk %}">
            {% include 'piece/card_gallery.html' with gallery=gallery %}
        </a>
        {% endfor %}
    </div>
    <script src="{% static 'js/magicgrid.js' %}"></script>
    {% else %}
    <div class="text-center">
        <h1>No Gallery YET!</h1>
    </div>
    {% endif %}

    {% include 'piece/pagination.html' with page_obj=page_obj %}

    <div style="text-align: center">
        <a href="{% url 'galleryapp:create' %}" class="btn btn-dark rounded-pill mt-3 mb-3 px-3">
            Create Gallery
        </a>
    </div>

{% endblock %}

galleryapp/templates/galleryapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

  <div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div class="mb-4">
      <h4>갤러리 수정</h4><!-- 이부분만 account 의 html 손좀 봄 -->
    </div>
    <form action="{% url 'galleryapp:update' pk=target_gallery.pk %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
  </div>

{% endblock %}