accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from . import views

app_name = "accountapp"

urlpatterns = [
    path('', views.hello_world, name='hello_world'),
    path('create/', views.AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', views.AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', views.AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.AccountDeleteView.as_view(), name='delete'),
    path('login/', LoginView.as_view(template_name = 'accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name = 'logout'),


]

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = 'articleapp'

urlpatterns = [
     path('list/', views.ArticleListView.as_view(), name='list'),
     path('create/', views.ArticleCreateView.as_view(), name='create'),
     path('detail/<int:pk>/', views.ArticleDetailView.as_view(), name='detail'),
     path('update/<int:pk>/', views.ArticleUpdateView.as_view(), name='update'),

     path('delete/<int:pk>/', views.ArticleDeleteView.as_view(), name='delete'),

]

galleryapp/urls.py
from django.urls import path
from . import views

app_name = 'galleryapp'

urlpatterns = [
    path('create/', views.GalleryCreateView.as_view(), name='create'),
    path('detail/<int:pk>/', views.GalleryDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', views.GalleryUpdateView.as_view(), name='update'),
    path('list/', views.GalleryListView.as_view(), name='list'),

]

infoapp/urls.py
from django.urls import path
from . import views

app_name = 'infoapp'

urlpatterns = [

    path('info/', views.info, name='info'),
    path('notice/', views.notice, name='notice'),
    path('contact/', views.contact, name='contact'),
    path('company/', views.company, name='company'),
]

subscribeapp/urls.py
from django.urls import path
from . import views

app_name='subscribeapp'

urlpatterns = [
    path('subscribe/', views.SubscriptionView.as_view(), name='subscribe'),
    path('list/', views.SubscriptionListView.as_view(), name='list'),
]

zzalbang/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView, ArticleMainList

urlpatterns = [
    path('', ArticleMainList.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include("accountapp.urls")),
    path('profiles/', include("profileapp.urls")),
    path('articles/', include('articleapp.urls')),
    path('comments/', include("commentapp.urls")),
    path('gallery/', include("galleryapp.urls")),
    path('subscribe/', include("subscribeapp.urls")),
    path('likes/', include("likeapp.urls")),

    path('infos/', include("infoapp.urls")),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path('summernote/', include('django_summernote.urls')),

]

templates/base.html
<!DOCTYPE html>
<html lang="ko">
{% include 'head.html' %}
<body>
{% include 'header.html' %}
<hr />


{% block content %}

{% endblock %}
<hr />
{% include 'footer.html' %}
</body>
</html>

templates/footer.html
<div class="window4sns_footer">
    <div class="window4sns_footer_button" >
        <!--<span><a href="{% url 'infoapp:notice' %}">공지사항</a></span> |-->
        <span><a href="{% url 'infoapp:info' %}">공지사항</a></span> |
        <span><a href="{% url 'infoapp:contact' %}">사업문의</a></span> |
        <span><a href="{% url 'infoapp:company' %}">서비스소개</a></span>


    </div>
    <div style="margin-top: 1rem;">
        <h6 class="window4sns_logo">Window4SNS 중소기업SNS__ www.3zzal.com</h6>
    </div>
</div>

templates/head.html
{% load static %}
<head>

    <meta charset="UTF-8">
    <title>3zzal.com</title>
    <!--  부트스트랩 링크 CDN 방식  -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!--  구글폰트 링크 CDN 방식 -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">

    <!-- 앱폴더가 아닌 루트폴더 바로 아래의 찾기시작작staic 폴더의 base.css -->
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}" />

    <link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet">

    <!-- 실제 디바이스 너비에 맞춰서 간격을 맞추고겠다는 뜻 -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- jQuery CDN -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">

    <!-- 폰트어섬 -->

    <script src="https://kit.fontawesome.com/5ae1a89e0e.js" crossorigin="anonymous"></script>



</head>

templates/header.html
<div  class="window4sns_header">
    <div>
        <a href="/">
            <h1 class="window4sns_logo"><span style="font-family: 'Noto Sans KR', sans-serif;">중소기업</span>SNS__3zzal.com</h1>
        </a>

    </div>
    <div>
        <a href="{% url 'articleapp:list'%}?st=hot" class="window4sns_header_nav">
            <span>
                hit게시글
            </span>

            <!-- <a href="{% url 'articleapp:list'%}?st=day">  <span> Today게시글   </span>     -->
        </a>
        <a href="{% url 'galleryapp:list' %}" class="window4sns_header_nav">
            <span>
                갤러리
            </span>

        </a>
        <a href="{% url 'subscribeapp:list' %}"  class="window4sns_header_nav">
            <span>
                구독리스트
            </span>
        </a>
        {% if not user.is_authenticated %}
        <!-- ?next 파라미터의 값 즉 현재위치로 리다이렉트 -->
              <a href="{% url 'accountapp:create' %}">
                <span>
                    SignUp
                </span>
              </a>
        <!--그 자리에서 로그인,  그 후에도 그 자리로 로딩-->
        <a href="{% url 'accountapp:login' %}?next={{ request.path }}" class="window4sns_header_nav">
                <span>
                    Login
                </span>
            </a>


        {% else %}
            <a href="{% url 'accountapp:logout' %}?next={{ request.path}}" class="window4sns_header_nav">
                <span>
                     Logout
                </span>
            </a>
             <a href="{% url 'accountapp:detail'  pk=user.pk %}">
                <span>
                    My Page
                </span>
            </a>
        {% endif %}
    </div>
</div>

templates/notice.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
공지사항

제휴문의

서비스 소개
</body>
</html>