articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = 'articleapp'

urlpatterns = [
     path('list/', views.ArticleListView.as_view(), name='list'),
     path('create/', views.ArticleCreateView.as_view(), name='create'),
     path('detail/<int:pk>/', views.ArticleDetailView.as_view(), name='detail'),
     path('update/<int:pk>/', views.ArticleUpdateView.as_view(), name='update'),

     path('delete/<int:pk>/', views.ArticleDeleteView.as_view(), name='delete'),

]

galleryapp/urls.py
from django.urls import path
from . import views

app_name = 'galleryapp'

urlpatterns = [
    path('create/', views.GalleryCreateView.as_view(), name='create'),
    path('detail/<int:pk>/', views.GalleryDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', views.GalleryUpdateView.as_view(), name='update'),
    path('list/', views.GalleryListView.as_view(), name='list'),

]

infoapp/urls.py
from django.urls import path
from . import views

app_name = 'infoapp'

urlpatterns = [

    path('info/', views.info, name='info'),
    path('notice/', views.notice, name='notice'),
    path('contact/', views.contact, name='contact'),
    path('company/', views.company, name='company'),
]

likeapp/urls.py
from . import views
from django.urls import path

app_name = 'likeapp'

urlpatterns = [
    path('article/like/<int:pk>/', views.LikeArticleView.as_view(), name='article_like')

]

zzalbang/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from articleapp.views import ArticleListView, ArticleMainList

urlpatterns = [
    path('', ArticleMainList.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include("accountapp.urls")),
    path('profiles/', include("profileapp.urls")),
    path('articles/', include('articleapp.urls')),
    path('comments/', include("commentapp.urls")),
    path('gallery/', include("galleryapp.urls")),
    path('subscribe/', include("subscribeapp.urls")),
    path('likes/', include("likeapp.urls")),

    path('infos/', include("infoapp.urls")),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path('summernote/', include('django_summernote.urls')),

]

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models

from galleryapp.models import Gallery


class Article(models.Model):
    #유저객체와 포린키로 연결, 유저가 탈퇴해도 게시글은 사라지지 않는다
    #유저객체에서 Article객체에 접근할 때 쓸 이름은 article, set_NULL으로 한다고 했으니 당연히 null=True 입력해줘야함
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='ariticle', null=True)
    title = models.CharField(max_length=200)
    #저장위지 반드시 저장
    image = models.ImageField(upload_to='article/', null=False)
    #내용작성 필드
    content = models.TextField(null=True, blank=True)
    #작성날짜, add로 게시글 생성했을 때의 시간으로 저장됨.
    created_at = models.DateTimeField(auto_now_add=True)


    #갤러리 객체와 포린키로 연결.  갤러리 지워저도 article들 안지워짐, 갤러리로 부터 article을 참조하는 역참조(related name) 이름은 article
    gallery = models.ForeignKey(Gallery, on_delete=models.SET_NULL, null=True, blank=True, related_name='article')

    like = models.IntegerField(default=0)


    def __str__(self):
        return self.title

articleapp/forms.py
from django.forms import ModelForm
from django_summernote.widgets import SummernoteWidget

from articleapp.models import Article


class ArticleCreationForm(ModelForm):
      #Meta정보를 활용할 때 Meta클래스 안에서 작성
    class Meta:
        #Article 모델을 이용해서 html 입력 Form 만들 것임
        model = Article
        # html 입력폼에서 사용자(user)로 부터 title, image, conten를 입력한다.  이 모든 것이 장고가 db에 저장
        fields = ['title', 'image', 'content']

        #서머노트 .   widget 속성으로 만들어질 폼에 스타일등을 정해줄 수 있다.
        widgets = {
            'content': SummernoteWidget()
        }

        # lables 속성으로 html에서 나타나는 필드 입력폼칸의 이름을 바꿔 줄 수 있다.
        labels = {
            'title': '제목',
            'image': '사진',
            'content': '내용'
       }

articleapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView, ListView
from django.views.generic.edit import FormMixin

from articleapp.decorators import article_ownership_required
from articleapp.forms import ArticleCreationForm
from articleapp.models import Article
from commentapp.forms import CommentCreationForm
from galleryapp.models import Gallery


@method_decorator(login_required, 'get')
@method_decorator(login_required, 'post')
class ArticleCreateView(CreateView):
    # 모델은 Article을 쓸 것이다
    model = Article
    # 입력폼은 ArticleCreationForm을 이용할 것이다
    form_class = ArticleCreationForm
    #ArticleCreationForm을 찍어낼  html은 articleapp 안의 create.html
    template_name = 'articleapp/create.html'


    #유효성 검사 메소드 form_valid를 오버라이딩

    def form_valid(self, form):
        # Article 객체를 저장하기전에 잠깐 멈춤!
        temp_article = form.save(commit=False)
        # Artcle 객체의 writer필드를 채우기
        temp_article.writer = self.request.user
        # 원래 제공 함수의 self.object = form.save() 대신에

        temp_article.gallery = Gallery.objects.get(pk=self.request.POST['gallery_pk'])
        temp_article.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('articleapp:detail', kwargs={'pk': self.object.pk})

class ArticleDetailView(DetailView, FormMixin):
    #어떤 모델을 쓸 것인가
    model = Article
    #이 위의 특정 Ariticel 객체를 찍어내는 html은 어떤 html을 쓸 것인가
    template_name = 'articleapp/detail.html'
    # {{모델명_detail}}안쓰고, 위의 html 에서 특정 Article 객체를 어떤 으름으로 {{}}안쪽 써서 표현할 것인가
    context_object_name = 'target_article'
    #위의 html에서 찍어낼 Form은 CommentCreationForm이다
    form_class = CommentCreationForm


@method_decorator(article_ownership_required, 'get')
@method_decorator(article_ownership_required, 'post')
class ArticleUpdateView(UpdateView):
    #모델은 Article을 쓸 것인가
    model = Article
    #Article 수정할 때 입력받은 폼은 ArticleCreationForm 을 쓸 것이다
    form_class = ArticleCreationForm
    # ArticleCreationForm을 찍어낼 html은 articleapp 폴더안의 update.html
    template_name = 'articleapp/update.html'
    context_object_name = 'target_article'

    def get_success_url(self):
        # 성공 후 돌아가는 페이지
        return reverse('articleapp:detail', kwargs={'pk': self.object.pk})


@method_decorator(article_ownership_required, 'get')
@method_decorator(article_ownership_required, 'post')
class ArticleDeleteView(DeleteView):
    #모델은 Article을 쓸 것이다
    model = Article
    #게시글 삭제할 버튼이 있는 html은 articleapp폴더 안의 delete.html이다
    template_name = 'articleapp/delete.html'
    #위의 html에서 특정 Article객체는 어떤 이름으로 표현할 것인가
    context_object_name = 'target_article'
    #게시글 삭제가 성공한다면 이동하게될 위치 지정
    #lazy는 딕셔너리 자료 인풋이 아닌 kwargs아닌 때
    success_url = reverse_lazy('articleapp:list')


class ArticleListView(ListView):
    #모델은 Article을 쓸 것이다
    model = Article
    #Article리스트 뭉탱이를 찍어내는 html은 어떤 htmal을 쓸 것인가
    template_name = 'articleapp/list.html'
    #위의 html에서 어떤 이름으로 Article리스트 뭉탱이를 표현할 것인가?
    context_object_name = 'article_list'
    #5개 단위로 리스트 뭉탱이 만들기
    paginate_by = 12

    #최신글을 앞에,  오랜 글은 뒤로
    ordering = '-pk'


    def get_queryset(self):
        if self.request.GET['st'] == 'hot':
            article_list = Article.objects.all().order_by('-pk')
        elif self.request.GET['st'] == 'day':
            article_list = Article.objects.filter(created_at__gte=timezone.now() - timezone.timedelta(day=1)).order_by('-like')
        elif self.request.GET['st'] == 'week':
            article_list = Article.objects.filter(created_at__gte=timezone.now() - timezone.timedelta(day=7)).order_by('-like')
        elif self.request.GET['st'] == 'month':
            article_list = Article.objects.filter(created_at__gte=timezone.now() - timezone.timedelta(day=30)).order_by('-like')

        return article_list

class ArticleMainList(ListView):
    model = Article
    context_object_name = 'article_list'
    template_name = 'articleapp/list.html'
    paginate_by = '24'
    ordering = '-pk'

articleapp/templates/articleapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

  <div style="text-align: center; max-width: 850px; margin: 4rem auto">
    <div class="mb-4">
      <h4>Article Create</h4>
    </div>
    <form action="{% url 'articleapp:create' %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="hidden" id="gallery_pk" value="" name="gallery_pk" >
      <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
  </div>

<script>
    // url 중에서 쿼리스트링 부분 가져오기 그러니까 ?로 시작하는 부분에서 끝까지 다 가져옴
    var search = location.search;
    // URLSearchParams 은 url 쿼리 문자열에 대해서 작업하는 것을 도와준다.
    var params = new URLSearchParams(search);
    // url 쿼리스트링 중에서 키가 'gallery_pk' 것의 '값' 을 getType 변수에 저장
    var getType = params.get('gallery_pk');
    // input 타입 히든인 태그를 아이디로 선택한다음 target 변수에 저장
    var target = document.getElementById("gallery_pk");
    // input 타입 히든의 속성 value 의 값에 getType 의 값을 채워 넣는다. 즉 위 html 에서 value="" 여기의 "" 안에다가 채워 넣는다는 뜻.
    target.setAttribute("value", getType);
  </script>

{% endblock %}

articleapp/templates/articleapp/delete.html
{% extends 'base.html' %}

{% block content %}

  <div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div class="mb-4">
      <h4>Delete Article : {{ target_article.title }}</h4>
    </div>
    <form action="{% url 'articleapp:delete' pk=target_article.pk %}" method="post">
      {% csrf_token %}
      <input type="submit" class="btn btn-danger rounded-pill col-6 mt-3">
    </form>
  </div>

{% endblock %}

articleapp/templates/articleapp/detail.html
{% extends 'base.html' %}


{% block content %}
  <div>
    <h1 style="text-align: center;">
      <a class="btn btn-dark" style="display:block; max-width:500px; margin: -17px auto 0px auto" href="{% url 'galleryapp:detail' pk=target_article.gallery.pk %}">
        {{ target_article.gallery.title }}
      </a>


    </h1>
    {% for message in messages %}
      <div class="text-center">
          <div class="btn btn-{{ message.tags }} rounded-pill px-5 my-3">
              {{ message }}
          </div>
      </div>
    {% endfor %}

    <div style="text-align: center; max-width: 850px; margin: 4rem auto;">
      <h1>
        {{ target_article.title }}
      </h1>
      <div style="height: 2rem;">
        <a href="{% url 'likeapp:article_like' pk=target_article.pk %}">
          <i class="material-icons" style="color: #f77; font-size: 1.2rem; vertical-align: middle;">
            favorite
          </i>
          <span style="vertical-align: middle; font-size: 1.2rem;">
            {{ target_article.like}}
          </span>
        </a>

      </div>

      <img width="100%" src="{{ target_article.image.url }}" alt="">

      <p>
        {{ target_article.content | safe }}
      </p>
      <div class="d-flex">
            <div class="badge badge-light p-2 ml-auto">
                <div>{{ target_article.created_at }}</div>

            </div>


      </div>
      <!-- 게시글 작성자가 진짜 작성한 유저인지 검증라인 -->
      {% if target_article.writer == request.user %}

      <a title="수정" style="box-shadow: 0 0 4px #ccc; border-radius: 50%; padding: 0.4rem;" class="material-icons" href="{% url 'articleapp:update' pk=target_article.pk %}">
        edit
      </a>
      &nbsp;
      <a title="삭제" style="box-shadow: 0 0 4px #ccc; border-radius: 50%; padding: 0.4rem;"class="material-icons" href="{% url 'articleapp:delete' pk=target_article.pk %}">
        cancel
      </a>

      {% endif %}

      {% for comment in target_article.comment.all %}
      <!-- with 구문에서 = 기준에서 왼쪽에 있는 comment 는 commentapp/detail.html에 있는 comment-->
        {% include 'commentapp/detail.html' with comment=comment %}
      {% endfor %}

    {% include 'commentapp/create.html' with article=target_article %}

    </div>



  </div>
{% endblock %}

articleapp/templates/articleapp/list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style>

    .container {
        padding: 0;
        margin: 0, auto;
    }

    .container a {
      width: 45%;
      max-width: 250px;
    }

    .container div {
      display: flex;
      justify-content: center;
      align-items: center;

      border-radius: 1rem;
    }

    .container img {
      width: 100%;
      border-radius: 1rem;
    }

    .article_like, .article_comment {
        display: inline;
        vertical-align: middle;
        color: rgb(49, 40, 40);
        font-size: 1.05rem !important;
    }

    .card_bot {
        box-shadow: 0 4px 4px -4px black;
    }





</style>
    {% if article_list %}
    <div class="container">
        {% for article in article_list %}
        {% if article.like > 0 %}
        <a href="{% url 'articleapp:detail' pk=article.pk %}">
            {% include 'piece/card.html' with article=article %}
            <div class="card_bot">
                <span>
                    <i style="color: #f77; vertical-align: bottom;" class="material-icons">favorite</i>
                    <p class="article_like" >{{ article.like }}</p>
                    <i style="color: #6b6b6b; vertical-align: bottom;" class="material-icons">comment</i>
                    {% if article.comment.count > 0 %}
                    <p class="article_comment">{{ article.comment.count }}</p>
                    {% else %}
                    <p class="article_comment">0</p>
                    {% endif %}
                </span>
            </div>
        </a>
        {% endif %}
        {% endfor %}
    </div>
    <script src="{% static 'js/magicgrid.js' %}"></script>
    {% else %}
    <div class="text-center">
        <h1>게시글이 없습니다.</h1>
    </div>
    {% endif %}

    {% include 'piece/pagination.html' with page_obj=page_obj %}

{% endblock %}

articleapp/templates/articleapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

  <div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div class="mb-4">
      <h4>Article Update</h4>
    </div>
    <!-- articleapp 의 update 라우트로 post 요청을 보낼것이다 -->
    <form action="{% url 'articleapp:update' pk=target_article.pk %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
  </div>

{% endblock %}